name: Deploy mewcrazy/StripChat-Enhanced

on:
  push:
    branches:
      - '**'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: write
      
    steps:
      # Step 1: Download waitForKeyElements.js
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Downloading waitForKeyElements.js
        run: chmod +x build/build.sh && build/build.sh

      # Step 2: Remove Google API Key from codebase
      - name: Remove Google API Key from codebase
        id: remove_api_keys
        run: sed -i -e 's/var googleApiKey = "${{ secrets.GOOGLE_TRANSLATION_APIKEY }}"/var googleApiKey = ""/g' extensions/chrome/foreground.js

      # Step 3: Insert version numbers into Chrome Extension
      - name: Insert version numbers into Chrome Extension
        id: insert_version_numbers
        run: |
          sed -i -e 's/version="[0-9]\+\.[0-9]\+\.[0-9]\+" \/>/version="${{ github.ref_name }}" \/>/g' extensions/chrome/updates.xml
          sed -i -e 's/"version": "[0-9]\+\.[0-9]\+\.[0-9]\+"/"version": "${{ github.ref_name }}"/g' extensions/chrome/manifest.json

      # Step 4: Check for any changes
      - name: Check for any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      # Step 5: Commit
      - name: Commit files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.name mewcrazy
          git config --local user.email "kontakt@dennis-bitsch.de"      
          git fetch
          git add extensions/chrome/js/waitForKeyElements.min.js
          git add extensions/chrome/js/jquery.min.js
          git commit -am "Update repository files [skip ci]"
          git push -f origin ${{ github.ref }}

      # Step 6: Push
      - name: Push to GitHub
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
        
      # Step 7: Generate Personal Access Token 
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # Step 8: Use Personal Access Token 
      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api octocat

      # Step 7: Release pushed tag
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              "extensions/chrome.crx#chrome_extension_$tag.crx" \
              "extensions/firefox.zip#firefox_extension_$tag.zip" \
              "extensions/opera.crx#opera_extension_$tag.crx" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
          
      # Step 7: Change Default Branch
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          tag: ${{ github.ref_name }}
        run: |
          gh repo edit --default-branch $tag